comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true

ignore:
  - "iStocksTests/Helpers/*"
  - "iStocksIntegrationTests/*"
  - "iStocks/Resources/*"
  - "iStocks.xcodeproj/*"
  - "DerivedData/*"

codecov:
  require_ci_to_pass: yes

fixes:
  - "/Users/runner/work/iStocks/iStocks/::"
