comment: false
coverage:
  status:
    project:
      default:
        target: auto
  parsers:
    gcov:
      branch_detection:
        conditional: true
        loop: true
  ignore:
    - "iStocksTests/Helpers/*"
    - "iStocksIntegrationTests/*"
    - "iStocks/Resources/*"
    - "iStocks.xcodeproj/*"
    - "DerivedData/*"
