# SwiftLint Configuration File

included:
  - iStocks
  - iStocksTests
  - iStocksIntegrationTests

excluded:
  - Pods
  - DerivedData
  - .build

opt_in_rules: # Optional strict rules that are not enabled by default
  - empty_count
  - explicit_init
  - joined_default_parameter
  - unneeded_break_in_switch

disabled_rules: # Common relaxed rules for flexibility
  - trailing_whitespace
  - line_length
  - identifier_name
  - function_body_length

reporter: xcode # Makes output format friendly for Xcode
