workflows:
  ios-workflow:
    name: iStocks iOS Build
    environment:
      xcode: 15.2
    scripts:
      - name: Resolve Swift Package dependencies
        script: |
          xcodebuild -resolvePackageDependencies \
            -project iStocks.xcodeproj \
            -scheme iStocks

      - name: Clean Build
        script: |
          xcodebuild clean \
            -project iStocks.xcodeproj \
            -scheme iStocks

      - name: Run Unit Tests
        script: |
          xcodebuild test \
            -project iStocks.xcodeproj \
            -scheme iStocks \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
          
    artifacts:
      - build/ios/ipa/*.ipa

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
